AM_Assignment2/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AM_Assignment2.Helpers;

namespace AM_Assignment2
{
    public class QuizController : Controller
    {
        // GET: Quiz
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        // Controller

        [HttpPost]
        public ActionResult Results(string Answer1, string Answer2, string Answer3, string Answer4, string Answer5, string Answer6, string userEmail)
        {
            bool answer1Result;
            bool answer2Result;
            bool answer3Result;
            bool answer4Result;
            bool answer5Result;
            bool answer6Result;
            ViewData["Answer1"] = Answer1;
            if (Answer1 == "A")
            {
                ViewData["Answer1Result"] = "/Content/Images/checkmark.png";
                answer1Result = true;
            }
            else
            {
                ViewData["Answer1Result"] = "/Content/Images/x mark.png";
                answer1Result = false;

            }

            ViewData["Answer2"] = Answer2;
            if (Answer2 == "B")
            {
                ViewData["Answer2Result"] = "/Content/Images/checkmark.png";
                answer2Result = true;
            }
            else
            {
                ViewData["Answer2Result"] = "/Content/Images/x mark.png";
                answer2Result = false;

            }
            ViewData["Answer3"] = Answer3;
            if (Answer3 == "A")
            {
                ViewData["Answer3Result"] = "/Content/Images/checkmark.png";
                answer3Result = true;
            }
            else
            {
                ViewData["Answer3Result"] = "/Content/Images/x mark.png";
                answer3Result = false;

            }
            ViewData["Answer4"] = Answer4;
            if (Answer4 == "C")
            {
                ViewData["Answer4Result"] = "/Content/Images/checkmark.png";
                answer4Result = true;
            }
            else
            {
                ViewData["Answer4Result"] = "/Content/Images/x mark.png";
                answer4Result = false;

            }
            ViewData["Answer5"] = Answer5;
            if (Answer5 == "A")
            {
                ViewData["Answer5Result"] = "/Content/Images/checkmark.png";
                answer5Result = true;
            }
            else
            {
                ViewData["Answer5Result"] = "/Content/Images/x mark.png";
                answer5Result = false;

            }
            ViewData["Answer6"] = Answer6;
            if (Answer6 == "C")
            {
                ViewData["Answer6Result"] = "/Content/Images/checkmark.png";
                answer6Result = true;
            }
            else
            {
                ViewData["Answer6Result"] = "/Content/Images/x mark.png";
                answer6Result = false;

            }
            UserQuery userQuery = new UserQuery();
            string userID = userQuery.GetUserIDByUserEmail(@User.Identity.Name);

            StatisticsQuery statsQuery = new StatisticsQuery();
            statsQuery.AddResults(answer1Result, answer2Result, answer3Result, answer4Result, answer5Result, answer6Result, userID); // Record results

            return View();
        }

    }
}

AM_Assignment2/Views/Quiz/Index.cshtml
@using System.Web.Mvc.Html;
@{
	ViewBag.Title = "Index";
}

<h2>It's time for a quiz!</h2>
<h3>You should only be here if you have completed the activities as the questions will be focused around them.</h3>
<br />


<h1>Quiz</h1>

	@using (Html.BeginForm("Results", "Quiz"))
	{
		<h3>Question One:</h3>
		<h4>What makes a semantic element semantic?</h4>
		@Html.RadioButton("Answer1", "A") <span>The name says what it is</span><br />
		@Html.RadioButton("Answer1", "B") <span>The name does not say what it is</span>
		<br />
		<h3>Question Two:</h3> 
		<h4>Which of the following is a semantic element?</h4>
		@Html.RadioButton("Answer2", "A") <span>Div</span><br />
		@Html.RadioButton("Answer2", "B") <span>Table</span><br />
		@Html.RadioButton("Answer2", "C") <span>Span</span>
		<br />
		<h3>Question Three:</h3>
		<h4>Was Autocomplete added as a Input Attribute in Html5?</h4>
		@Html.RadioButton("Answer3", "A") <span>Yes</span><br />
		@Html.RadioButton("Answer3", "B") <span>No</span>
		<br />
		<h3>Question Four:</h3>
		<h4>The ________ attribute specifies that the input field should automatically get focus when the page loads.</h4>
		@Html.RadioButton("Answer4", "A") <span>ZoneIn</span><br />
		@Html.RadioButton("Answer4", "B") <span>FocusAuto</span><br />
		@Html.RadioButton("Answer4", "C") <span>Autofocus</span>
		<br />
		<h3>Question Five:</h3>
		<h4>Which definition best fits the Web Form Structure element: number?</h4>
		@Html.RadioButton("Answer5", "A") <span>This accepts only a numerical value</span><br />
		@Html.RadioButton("Answer5", "B") <span>This accepts any numerical and/or alphabetical value</span><br />
		@Html.RadioButton("Answer5", "C") <span>This accepts only a alphabetical value</span>
		<br />
		<h3>Question Six:</h3>
		<h4>With the URL element, which of the following is the best answer for acceptable formatting?</h4>
		@Html.RadioButton("Answer6", "A") <span> http://example.com</span><br />
		@Html.RadioButton("Answer6", "B") <span> http://www.example.com</span><br />
		@Html.RadioButton("Answer6", "C") <span> BOTH of the above</span>
		<br />
		<br />
        <input type="hidden" value="@User.Identity.Name" name="userEmail"/>
		<input type="submit" value="Submit" />
	}

AM_Assignment2/Views/Quiz/Results.cshtml
@{
	ViewBag.Title = "Results";
}

<h2>Results</h2>
<p>Question One: </p>
<li>You selected @ViewData["Answer1"]</li>
<img src="@ViewData["Answer1Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>A</b>, The name says what it is</p>
<br />
<p>Question Two: </p>
<li>You selected @ViewData["Answer2"]</li>
<img src="@ViewData["Answer2Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>B</b>, Table</p>
<br />
<p>Question Three: </p>
<li>You selected @ViewData["Answer3"]</li>
<img src="@ViewData["Answer3Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>A</b>, Yes</p>
<br />
<p>Question Four: </p>
<li>You selected @ViewData["Answer4"]</li>
<img src="@ViewData["Answer4Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>C</b>, AutoFocus</p>
<br />
<p>Question Five: </p>
<li>You selected @ViewData["Answer5"]</li>
<img src="@ViewData["Answer5Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>A</b>, This accepts only a numerical value</p>
<br />
<p>Question Six: </p>
<li>You selected @ViewData["Answer6"]</li>
<img src="@ViewData["Answer6Result"]" width="50" height="50" style="margin:5px" />
<p>The correct answer was: <b>C</b>, BOTH of the above</p>
<br />