AM_Assignment2/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AM_Assignment2.DAL;
using AM_Assignment2.Models;
using AM_Assignment2.Helpers;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace AM_Assignment2.Controllers
{
    // Create, Read, Update and Delete functionality for Groups
    [Authorize(Roles = "Administrator")] // Secure to administrators only
    public class GroupController : Controller
    {
        private ApplicationUserManager _userManager;
        private App_Database db = new App_Database();

        // GET: Group
        public ActionResult Index()
        {
            return View(db.Group.ToList());
        }

        // GET: Group/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Group/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Group.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: Group/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Group/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,GroupName")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Group/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Group.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserQuery userQuery = new UserQuery();
            List<User> listOfUsersInGroup = userQuery.GetUserByGroup(id);
            List<string> userEmailList = new List<string>();
            if (listOfUsersInGroup.Count > 0) // If there are users still assigned to the group that's being deleted
            {
                foreach (var user in listOfUsersInGroup)
                {
                    userEmailList.Add(userQuery.GetUserEmailByUserID(user.UserID));
                }
                ViewData["UserEmailList"] = userEmailList;
                ViewData["UserIDList"] = listOfUsersInGroup;
                return RedirectToAction("UnsafeDeletion", new { groupID = id });
            }
            else // Delete group
            {
                Group group = db.Group.Find(id);
                db.Group.Remove(group);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: Group/UnsafeDeletion/groupID
        // Description: If admin tries to delete group that has users still assigned to it (referential integrity), then display the users affected
        [HttpGet]
        public ActionResult UnsafeDeletion(int groupID)
        {
            UserQuery userQuery = new UserQuery();
            List<User> qryResult = userQuery.GetUserByGroup(groupID); // Select all users in corresponding group
            List<ApplicationUser> userGroupList = new List<ApplicationUser>();

            // For each user with corresponding group ID
            foreach (var item in qryResult)
            {
                ApplicationUser identity_user = UserManager.FindById(item.UserID); // Get user from identity database
                userGroupList.Add(identity_user);
            }

            ViewData["UsersInGroup"] = userGroupList; // For View
            return View();
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AM_Assignment2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_Assignment2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "HTML5 4 NOOBS is an interactive website designed to introduce users to core HTML concepts";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AM_Assignment2/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AM_Assignment2.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }

        // GET: Statistics/ViewStats
        public ActionResult ViewStats()
        {
            return View();
        }
    }
}

AM_Assignment2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Created by Shan Weeraratne, Tom Weake and Nicholas Scott.</p>

AM_Assignment2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AM_Assignment2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        <div class="row" style="align-items:center; padding-top:20px; align-self: center; background-color:#E3B628">
                <h1 style="color:darkred; font-weight: bold; float:left; margin-left:20px;position: relative; top: 50%;transform: translateY(-50%);">
                    Administrator Settings
                </h1>

                @Html.ActionLink("Show users", "ShowUsers", "Account");

                @Html.ActionLink("Create user", "Register", "Account");

                @Html.ActionLink("Group management", "Index", "Group");
                

            </div>
    }
    if (HttpContext.Current.User.IsInRole("Instructor"))
    {
        <div class="row" style="align-items:center; padding-top:20px; align-self: center; background-color:#E3B628">

            @Html.ActionLink("View stats", "ViewStats", "Statistics");
        </div>
    }
}

<div class="jumbotron" style="text-align:center; background: linear-gradient(#662D8C, #ED1E79); margin-bottom:10px;">
    <h1 style="color:antiquewhite">Welcome to HTML5 4 Noobs</h1>
    <p class="lead" style="text-align:center; color:antiquewhite">Here, you will be able to learn the fundamentals of HTML5 </p>
</div>

<div class="jumbotron" style="text-align:center; background: #FFF;margin-bottom:10px;">
    <h1 style="color:#000">Your Learning Outcomes</h1>
    <p class="lead" style="text-align:center;color:#000">To be able to understand HTML5 semantics, input attributes and Web Form Stuctures</p>
</div>

<div class="row" style="margin-bottom:5px">
    <div class="col-md-4" style="text-align:center;background: linear-gradient(#D4145A, #FBB03B);" >
        <h2 style="font-weight: bold">Activity 1</h2>
        <p style="color:antiquewhite; font-weight: bold; font-size:24px;">
            Semantics
        </p>
            <img src="~/Content/Images/HTML5logo.png" width="125" height="125" style="margin:5px" />
        <p><a class="btn btn-default"  style="text-align:center;background: #2E3192; color:antiquewhite;font-weight:bolder "
              href="/ActivityOne">Start Activity 1&raquo;</a></p>
    </div>

    <div class="col-md-4" style="text-align:center;background: linear-gradient(#2E3192 ,#1BFFFF);">
        <h2 style="font-weight: bold">Activity 2</h2>
        <p style="color:antiquewhite; font-weight: bold; font-size:24px;">
            Input attributes
        </p>
        <img src="~/Content/Images/HTML5logo.png" width="125" height="125" style="margin:5px   " />
        <p>
            <a class="btn btn-default" style="text-align:center;background:#2E3192;color:antiquewhite;font-weight:bolder "
               href="/ActivityTwo">Start Activity 2&raquo;</a>
        </p>
    </div>

    <div class="col-md-4"style="text-align:center;background: linear-gradient(#009245,#FCEE21);">
        <h2 style="font-weight: bold">Activity 3</h2>
        <p style="color:antiquewhite; font-weight: bold; font-size:24px;">
            Web Form Stuctures
        </p>
        <img src="~/Content/Images/HTML5logo.png" width="125" height="125" style="margin:5px" />
        <p>
        <a class="btn btn-default" style="text-align:center;background:#2E3192;color:antiquewhite;font-weight:bolder "
           href="/ActivityThree">Start Activity 3&raquo;</a>
        </p>
    </div>
</div>